### ISSUE TITLE
Brak mozliwosci customizacji elementow

### ISSUE THREAD

**Issue by Jhoczi** [HIWIG/Monopoly#7]
Nie wiem czy to wina ostatniego patcha, ale stracilem mozliwosc zakupu mikrotransakcji...

Naprawcie plz.

**Comment by HIWIG** [comment]
Transakcje można przelać bezpośrednio na konto, wysyłam w wiadomości priv

**Comment by Jhoczi** [comment]
Zamykam zatem.
